spring:
  application:
    name: turbine
server:
  port: 9004
turbine:
  app-config: some,some2 #配置Eureka中的serviceId列表，表明监控哪些服务
  aggregator:
    clusterConfig: default #指定聚合哪些集群，多个使用”,”分割，默认为default。
  cluster-name-expression:  new String("default")  # 1. clusterNameExpression指定集群名称，默认表达式appName
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8000/eureka/