---
spring:
  application:
    name:  discovery
  #profiles: peer1
server:
    port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #是否将自己注册到Eureka server， 默认为true
    fetch-registry: false #是否从 Eureka Server中获取信息默认为true
    #serviceUrl:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      #defaultZone: http://peer2:8001/eureka,http://peer3:8002/eureka
#---
#spring:
#  application:
#    name:  discovery
#  profiles: peer2
#server:
#    port: 8001
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    #register-with-eureka: false  #是否将自己注册到Eureka server， 默认为true
#    #fetch-registry: false #是否从 Eureka Server中获取信息默认为true
#    serviceUrl:
#      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
#      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name:  discovery
#  profiles: peer3
#server:
#    port: 8002
#eureka:
#  instance:
#    hostname: peer3
#  client:
#    #register-with-eureka: false  #是否将自己注册到Eureka server， 默认为true
#    #fetch-registry: false #是否从 Eureka Server中获取信息默认为true
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/